config/routes.rb
Rails.application.routes.draw do
 
  #hypens pour seo - link canonical dans layout 
  get 'location-bateau-cannes', to: 'article#location_bateau_cannes'
  get 'louer-bateau-cannes', to: 'article#location_bateau_cannes'
  #get 'article/location_bateau_cannes'

  get 'location-bateau-mandelieu', to: 'article#location_bateau_mandelieu'
  get 'louer-bateau-mandelieu', to: 'article#location_bateau_mandelieu'

  get 'location-bateau-antibes', to: 'article#location_bateau_antibes'
  get 'louer-bateau-antibes', to: 'article#location_bateau_antibes'
  
  get 'evenement-nautique-cote-d-azur-cannes-antibes-mandelieu', to: 'article#organisation_evenements'
  get 'sejour-en-mer-cote-d-azur-cannes-antibes-mandelieu-', to: 'article#organisation_evenements'
  get 'journee-en-bateau-cote-d-azur-cannes-antibes-mandelieu-', to: 'article#organisation_evenements'

  
  get 'evenement/index'
  
  get 'home/index'
  get 'home/indexdesign2'


  get "blog/index"

  get 'home/mentions_legales'
  get 'home/nous_connaitre'
  get 'home/politique_confidentialite'
  
  get 'home/testimage'
  root "home#index"
  get 'espace_permis/index'
  
  get 'espace_bailleur/index'
  get 'espace_preneur/index'
  get 'espace_admin/index'

  get 'produits/archive', to: 'produits#archive', as: 'archive_produits'
  post 'produits/:id/activate', to: 'produits#activate', as: 'activate_produit'
  post 'produits/:id/archivate', to: 'produits#archivate', as: 'archivate_produit'
  get '/produits/:id/fullscreen', to: 'produits#fullscreen', as: 'produit_fullscreen'
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'users/show'
  get 'users/:id' => 'users#show', as: 'user'
  
  resources :destinations
  resources :bailleurs
  resources :preneurs
  resources :admin_parameters
  resources :demandes
  
  resources :produits do
    member do
     # post :edit
      get :edition
      get :delete_image1_attachment
    #  get 'delete_media_attachment/:media_id', action: :delete_media_attachment, as: :delete_media_attachment
      get 'delete_media_attachment', to: 'produits#delete_media_attachment', as: :delete_media_attachment
 
    end
  end

  resources :contrats do 
    member do
      get :edition
      get :edition_capitaine
    end
  end


  resources :occupations do
    member do
      post :edit
    end
  end

  resources :schedules do
    member do
      post :edit
    end
  end

  resources :reservations do
    member do
      get :edition
      get :edition_test

      get :send_reservation_email_preneur, 
          to: 'reservations#send_reservation_email_preneur', 
          as: :send_reservation_email_preneur

      get :send_reservation_email_bailleur, 
          to: 'reservations#send_reservation_email_bailleur', 
          as: :send_reservation_email_bailleur
    end
  end



end

app/controllers/espace_bailleur_controller.rb
class EspaceBailleurController < ApplicationController

  def index
    bailleur = Bailleur.where(user_id: current_user).first
    @produits = bailleur.produits if bailleur.present?
  end
  
end

app/helpers/espace_bailleur_helper.rb
module EspaceBailleurHelper
end

app/views/espace_bailleur/_etapes.html.erb
<div class="container mt-4">
    <%#= link_to new_user_registration_path(role: "proprietaire"), class: "no-underline" do %>
    <%= link_to new_demande_path(demandeId: "proprietaire"), class: "no-underline" do %>
        <div data-aos="zoom-in-up" class="bloc-etape">    
            <p class="card-text fs-1 m-1 my-3"> Etape 1</p>
            <p class="card-text fs-4 m-1 my-3"> Contactez-nous en nous fournissant quelques informations sur votre bateau </p>
        </div>
        <div  data-aos="zoom-in-up" class="bloc-etape">    
            <p class="card-text fs-1 m-1 my-3"> Etape 2</p>
            <p class="card-text fs-4 m-1 my-3"> Nous commercialisons votre bateau et gérons les locations </p>
        </div>
        <div  data-aos="zoom-in-up" class="bloc-etape">    
            <p class="card-text fs-1 m-1 my-3"> Etape 3</p>
            <p class="card-text fs-4 m-1 my-3"> Vous recevez votre argent en toute tranquillité</p>
        </div>
    <% end %>
</div>

app/views/espace_bailleur/_reservations.html.erb
<div data-aos="fade-up" data-aos-delay="100" class="container-parent">
    <div  data-aos="zoom-in-up" class="bloc-enfant">
        <div class="card" style="width: 18rem;">
        <%#= image_tag(produit.image1, class:"card-img-top") if produit.image1.present? %> 
            <div class="card-body">
                <p class="card-text fs-2 m-1">  nb locations: <%= reservations_count %> </p>
                <p class="card-text fs-4 m-1"> locations clôturées: <%= reservations_count  %> </p>
                <p class="card-text fs-4 m-1"> locations à venir: <%= reservations_count  %> </p>
            </div>
        </div>
    </div>

    <% reservations_bailleur_courant.each do |reservation| %>
        <%= link_to reservation_path(reservation) do %>
            <div  data-aos="zoom-in-up" class="bloc-enfant">
                <div class="card" style="width: 18rem;">
                    <%#= image_tag(produit.image1, class:"card-img-top") if produit.image1.present? %> 
                    <div class="card-body">
                        <p class="card-text fs-3 m-1"> <%= preneur_full_name(reservation.preneur_id) %></p>
                        <p class="card-text fs-6 m-1"> <%= reservation.debutlocation %> - <%= reservation.finlocation %></p>
                        <p class="card-text fs-4 m-1"> Prix: <%= reservation.prix %></p>
                    </div>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/espace_bailleur/_statistiques.html.erb
<div class="container-parent">
    <div class="bloc-enfant">
        <div class="card" style="width: 18rem;">
            <%#= image_tag(produit.image1, class:"card-img-top") if produit.image1.present? %> 
            <div class="card-body">
                <p class="card-text fs-1 m-1"> nb bateaux: <%= produits_count %> </p>
                <p class="card-text fs-4 m-1"> nb réservations: <%= reservations_count  %> </p>
                <p class="card-text fs-4 m-1"> val réservations: <%= reservations_val  %> </p>
            </div>
        </div>
    </div>

    <div class="bloc-enfant">
        <%= render "charts/chartLineResaBailleur" %>
    </div>

    <div class="bloc-enfant">
        <%= render "charts/chartPieResaBailleur" %>
    </div>

    <div class="bloc-enfant">
        <%= render "charts/chartBarResaBailleur" %>
    </div>
</div>

app/views/espace_bailleur/index.html.erb
<% description "Découvrez comment proposer votre bateau à la location avec Galayacht. Obtenez toutes les informations dont vous avez besoin pour commencer à générer des revenus en louant votre bateau" %>
<% keywords "Proposer bateau à la location, louer mon bateau, liste de bateau, gagner de l'argent avec mon bateau, partager mon bateau, location de bateau" %>

<h1 style="position: absolute; left: -9999px;"> 
  Proposer son bateau - Louer son bateau - location bateau cannes - partager bateau - gagner argent bateau 
</h1>


<%
=begin%>
 <h1 class="text-center mb-4"> Proposer son bateau </h1>
 
<%
=end%>
<%
=begin%>
 <% if user_bailleur.present? %>

    <h2 class="title m-1"> MES BATEAUX</h2>

    <div data-aos="zoom-in-up" class="container-parent">
        <% @produits.each do |produit| %>
            <%= link_to produit_path(produit) do %>
                <div class="bloc-enfant">
                    <div class="card" style="width: 18rem;">
                        <%= image_tag(produit.image1, class:"card-img-top") if produit.image1.present? %> 
                        <div class="card-body">
                            <p class="card-text fs-1 m-1"> <%= produit.nom %></p>
                            <p class="card-text fs-4 m-1"> Prix: <%= produit.prixjour %></p>
                            <p class="card-text fs-4 m-1"> <%= localisation_port(produit.destination_id) %></p>
                        </div>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>

    <div class="container-fluid width-limited text-start">    
        <%= link_to "Ajouter un bateau", new_produit_path, class: "btn btn-sm btn-primary fw-bold" %>
    </div>

    <hr>  

    <h2 class="title m-1"> MES LOCATIONS </h2>
    <%= render "reservations" %>
    <hr>

    <h2 class="title m-1"> MES STATISTIQUES </h2>
    <%= render "statistiques" %>
    <hr>
 
<%
=end%>
<%# else %>

    <div class="container container-margin">
        <%= render "etapes" %>
    </div>

    <hr>
    
<%
=begin%>
     <div data-aos="zoom-in-up" class="container">
        <div class= "text-center">
            <%= link_to 'Log in', new_user_session_path, class: "btn btn btn-warning fw-bold m-2" %>
            <%= link_to 'Create account', new_user_registration_path, class: "btn btn btn-primary fw-bold m-2" %>
        </div>
    </div>  
<%
=end%>       
    <hr>

<%# end %>