config/routes.rb
Rails.application.routes.draw do
 
  #hypens pour seo - link canonical dans layout 
  get 'location-bateau-cannes', to: 'article#location_bateau_cannes'
  get 'louer-bateau-cannes', to: 'article#location_bateau_cannes'
  #get 'article/location_bateau_cannes'

  get 'location-bateau-mandelieu', to: 'article#location_bateau_mandelieu'
  get 'louer-bateau-mandelieu', to: 'article#location_bateau_mandelieu'

  get 'location-bateau-antibes', to: 'article#location_bateau_antibes'
  get 'louer-bateau-antibes', to: 'article#location_bateau_antibes'
  
  get 'evenement-nautique-cote-d-azur-cannes-antibes-mandelieu', to: 'article#organisation_evenements'
  get 'sejour-en-mer-cote-d-azur-cannes-antibes-mandelieu-', to: 'article#organisation_evenements'
  get 'journee-en-bateau-cote-d-azur-cannes-antibes-mandelieu-', to: 'article#organisation_evenements'

  
  get 'evenement/index'
  
  get 'home/index'
  get 'home/indexdesign2'


  get "blog/index"

  get 'home/mentions_legales'
  get 'home/nous_connaitre'
  get 'home/politique_confidentialite'
  
  get 'home/testimage'
  root "home#index"
  get 'espace_permis/index'
  
  get 'espace_bailleur/index'
  get 'espace_preneur/index'
  get 'espace_admin/index'

  get 'produits/archive', to: 'produits#archive', as: 'archive_produits'
  post 'produits/:id/activate', to: 'produits#activate', as: 'activate_produit'
  post 'produits/:id/archivate', to: 'produits#archivate', as: 'archivate_produit'
  get '/produits/:id/fullscreen', to: 'produits#fullscreen', as: 'produit_fullscreen'
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'users/show'
  get 'users/:id' => 'users#show', as: 'user'
  
  resources :destinations
  resources :bailleurs
  resources :preneurs
  resources :admin_parameters
  resources :demandes
  
  resources :produits do
    member do
     # post :edit
      get :edition
      get :delete_image1_attachment
    #  get 'delete_media_attachment/:media_id', action: :delete_media_attachment, as: :delete_media_attachment
      get 'delete_media_attachment', to: 'produits#delete_media_attachment', as: :delete_media_attachment
 
    end
  end

  resources :contrats do 
    member do
      get :edition
      get :edition_capitaine
    end
  end


  resources :occupations do
    member do
      post :edit
    end
  end

  resources :schedules do
    member do
      post :edit
    end
  end

  resources :reservations do
    member do
      get :edition
      get :edition_test

      get :send_reservation_email_preneur, 
          to: 'reservations#send_reservation_email_preneur', 
          as: :send_reservation_email_preneur

      get :send_reservation_email_bailleur, 
          to: 'reservations#send_reservation_email_bailleur', 
          as: :send_reservation_email_bailleur
    end
  end



end

app/views/shared/_balise_google.html.erb
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-6ZZS49JPNV"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-6ZZS49JPNV');
</script>

app/views/shared/_contacts.html.erb
<div class="fw-bold text-center mt-2">
    <p>
        <i class="fa fa-xl fa-phone mx-2"></i>
        +33 (0) 626 210 213
    </p>

    <p>
        <i class="fa fa-xl fa-envelope mx-2"></i>
        <a href="mailto:contact@galayacht.com" class="no-underline">contact@galayacht.com</a>
    </p>
    <p>
        <i class="fa fa-xl fa-location-dot mx-2"></i>
        <a href="https://www.google.com/maps?q=27+Avenue+des+Fr%C3%A8res+Roustan,+06220+Golfe-Juan" class="no-underline">
        27 Avenue des Frères Roustan, 06220 Golfe-Juan</a>
    </p>
</div>

app/views/shared/_explications.html.erb
<div class="container p-3" style="max-width: 800px;">

  <div class="container mb-3">
    <%= image_tag("svgs/svg1.svg?#{Time.now.to_i}", 
      width: 250, height: 250, alt: "Animated GIF", 
      data: { controller: "reanimate", "reanimate-target": "gif" }) %>
  </div>

  <p>
    Bienvenue chez Galayacht, votre partenaire de confiance pour la location de yachts sur la splendide Côte d'Azur, 
    notamment à Cannes, Golfe Juan, Antibes, Mandelieu, et au-delà. 
    Notre société est spécialisée dans la location de yachts de prestige et l'organisation d'événements nautiques mémorables. 
    Nous sommes là pour concrétiser vos rêves maritimes, quel que soit la dimension de votre projet ou votre budget.
  </p>

  <div class="container my-4">
    <a class="btn btn-sm primary-colored m-2" data-bs-toggle="collapse" href="#collapseDetails" role="button" aria-expanded="false" aria-controls="collapseDetails">
      Voir plus de détails 
    </a>
    <div class="collapse" id="collapseDetails">
      <div class="card card-body bg-dark">
        Bienvenue chez Galayacht, votre partenaire de confiance pour la location et la vente de bateaux et yachts de prestige sur la Côte d'Azur. 
        Explorez Cannes, Golfe Juan, Antibes, Mandelieu, et bien d'autres destinations ensoleillées à bord de nos navires de première classe. 
        Nous organisons des événements nautiques mémorables, du mariage parfait à une sortie en mer en famille. 
        Choisissez Galayacht pour une expérience maritime d'exception. 
        Pour en savoir plus, contactez-nous et préparez-vous à naviguer vers l'aventure.
      </div>
    </div>
  </div>

  <p>
      Que vous souhaitiez louer un yacht, un voilier, ou un maxi-catamaran, 
      Galayacht vous offre une flotte de bateaux et de services associés d'une qualité exceptionnelle. 
      Notre équipe de professionnels passionnés se tient prête à répondre à toutes vos attentes, 
      que ce soit pour une location de bateau ou la planification d'un événement unique en mer.
  </p>


  <div class="container mb-3">
    <%= image_tag("svgs/svg2.svg?#{Time.now.to_i}", 
      width: 250, height: 250, alt: "Animated GIF", 
      data: { controller: "reanimate", "reanimate-target": "gif" }) %>
  </div>

  <p>
    Louer un yacht sur la Côte d'Azur est le choix idéal pour des événements privés ou publics. 
    Imaginez-vous à bord de votre propre yacht, amarré dans le port de Cannes, de Golfe Juan, d'Antibes, de Mandelieu, 
    profitant de moments uniques pour sublimer votre événement ou vous détendre en vacances. 
  </p>

  <div class="container my-4">
    <a class="btn btn-sm primary-colored m-2" data-bs-toggle="collapse" href="#collapseInfos" role="button" aria-expanded="false" aria-controls="collapseInfos">
      Plus d'informations 
    </a>
    <div class="collapse" id="collapseInfos">
      <div class="card card-body bg-dark">
        <div class="text-center m-2"> Les recherches que font nos clients :</div> 
        Location de yachts - Vente de bateaux de prestige - Côte d'Azur - Cannes - Golfe Juan - Antibes - Mandelieu - Événements nautiques
        - Mariages en mer - Sorties en famille - Naviguer en Méditerranée - Expérience maritime de luxe - Location de voiliers - Yachts à moteur - Aventures en mer - Locations sur mesure - Destinations ensoleillées
        - Escapades romantiques - Pêche en haute mer - Charters exclusifs - Vacances sur l'eau - Excursions en yacht - Plaisir de la navigation
        - Service de qualité - Experts en navigation - Flotte variée - Destinations de rêve - Exploration maritime 
        - Gala yacht - Galayacht - GALAYACHT - yacht gala -

      </div>
    </div>
  </div>

  <p>
    Chez Galayacht, nous mettons tout en œuvre pour que votre expérience soit inoubliable.
    Vous avez la flexibilité de louer un bateau pour une journée ou plusieurs semaines, 
    que ce soit pour une soirée glamour, un événement exclusif, ou des vacances en famille. 
    Nous sommes là pour créer un projet sur mesure, depuis la magnifique Côte d'Azur 
    jusqu'à d'autres destinations de rêve dans le monde entier.
    Optez pour Galayacht et découvrez le plaisir de la navigation ou toute tranquillité. 
  </p>

  <div class="container mb-3">
    <%= image_tag("svgs/svg3.svg?#{Time.now.to_i}", 
      width: 250, height: 250, alt: "Animated GIF", 
      data: { controller: "reanimate", "reanimate-target": "gif" }) %>
  </div>

  <p>
    Réservez dès maintenant votre yacht de rêve et préparez-vous à vivre des moments exceptionnels en mer. 
    Notre passion, c'est de rendre vos rêves de navigation réalité.  
    Pour une expérience maritime inoubliable, faites confiance à Galayacht, votre expert en location de bateaux.
  </p>

  <p>
    Cannes, location de bateau, location de yacht, louer un yacht, location de bateau à Cannes, location de yacht à Cannes, 
    louer un yacht à Cannes, location de bateau de luxe, louer un yacht de prestige, côte d'azur, 
    événements nautiques, Galayacht.
  </p>

</div>

<footer>
  <small>
    <p style="font-style: italic;">
      Icons by
      <a href="https://storyset.com/people">Animated illustrations by Storyset</a>
    </p>
  </small>   
</footer>

app/views/shared/_footer.html.erb
<div class="footer text-light">   
    <% if current_user.present? %>
        <%= link_to '', user_path(current_user.id), class: "fa-regular fa-user btn btn-light" %>

        <% if user_admin.present? %>
            Admin

        <% elsif user_preneur.present? %>
            <%= link_to user_path(current_user.id), class: "no-underline fs-6" do %>
                Locataire
            <% end %>
        <%# elsif user_bailleur.nil? %>
            <%#= link_to "Créer profile locataire", new_preneur_path, class: "text-center no-underline text-warning" %>
        <%# end %>
        <% elsif user_bailleur.present? %>
            <%= link_to user_path(current_user.id), class: "no-underline" do %>
                Bailleur
            <% end %>
         <%# elsif user_preneur.nil? %>
            <%#= link_to "Créer profile bailleur", new_bailleur_path, class: "text-center no-underline text-primary" %>
        <% end %>
        <%= button_to "", destroy_user_session_path, method: :delete, class: "fa-solid fa-right-from-bracket btn btn-danger"  %>
    <% else %>
        <%= link_to '', new_user_session_path, 
            class: "fa-solid fa-user-lock btn btn-warning",
            alt: "Sign in",
            'aria-label' => "Se connecter au compte" %>
        <%= link_to '', new_user_registration_path, class: "fa-solid fa-user-plus btn btn-primary" %>
    <% end %>  
</div>

app/views/shared/_form_submit.html.erb
<button type="submit" class="btn btn-success">
  <span><i class="fa-solid fa-square-check"></i> </span>
</button>

app/views/shared/_full_calendar.html.erb
<div class="card">

    <h4 class="text-center m-2"> Calendrier </h4>

<%
=begin%>
     <% if current_user && user_admin %>

        <div data-controller="newrecord" data-action="turbo:submit-end->newrecord#submitEnd">
            <div id="schedules" class="container-fluid">
                <% @schedules.each do |schedule| %>
                    <div class="row">
                        <div class="col-12 mb-1 px-4">
                            <%= render schedule %>
                        </div>
                    </div>
                <% end %>
            </div>

            <div class="p-2 px-4"> 
                <div role="button" data-action="click->newrecord#openDropdown" 
                    data-newrecord-target="openButton"class="btn btn-warning btn-action">
                    <i class="fas fa-solid fa-add me-2"></i>
                    <span class="text-md">Nouvelles dates</span>
                </div>
                <div role="button" data-action="click->newrecord#closeDropdown" 
                    data-newrecord-target="closeButton" 
                    class="btn btn-danger btn-action">
                    <i class="fa-solid fa-close me-2"></i>
                    <span class="text-md">Fermer</span>
                </div>

                <div data-newrecord-target="newrecordContent">
                    <div id="new_schedule">
                    <%= render partial: "schedules/form", locals: {schedule: Schedule.new} %>
                </div>
            </div>
        </div>
    <% end %> 
<%
=end%>

<%= render "shared/tui_calendar" %>

</div>

app/views/shared/_mentions_footer.html.erb
<div class="row">

    <small class="container text-light text-center my-3 p-4">
        <%= render "shared/explications" %>
    </small>
    
    <div class="col">
        <strong class="titre-footer">Rubriques</strong>
        <p class="mt-4"> <%= link_to "Aide", root_path, class: "link-mention" %> </p>  
        <p> <%= link_to "Nous connaitre", home_nous_connaitre_path, class: "link-mention" %> </p>    
        <p> <%= link_to "Nous contacter", new_demande_path, class: "link-mention" %> </p>        
        <p> <%= link_to "Nos services", root_path, class: "link-mention" %> </p>  
        <p> <%= link_to "Assurance", root_path, class: "link-mention" %> </p>  
        <p> <%= link_to "Politique de confidentialité", home_politique_confidentialite_path, class: "link-mention" %> </p>  
        <p> <%= link_to "CGU", root_path, class: "link-mention" %> </p>  
        <p> <%= link_to "Mentions légales", home_mentions_legales_path, class: "link-mention" %> </p>  
    </div>


    <div class="col">
         <strong class="titre-footer">Bateaux</strong>
        <p class="mt-4">  <%= link_to "Moteur", root_path, class: "link-mention" %> </p>  
        <p> <%= link_to "Voilier", root_path, class: "link-mention" %> </p>  
        <p> <%= link_to "Catamaran", root_path, class: "link-mention" %> </p>  
        <p> <%= link_to "Yacht", root_path, class: "link-mention" %> </p>  
    </div>

    <div class="col">
         <strong class="titre-footer">Destinations</strong>
        <p class="mt-4"> <%= link_to "Cannes", root_path, class: "link-mention" %> </p> 
        <p> <%= link_to "Golfe Juan", root_path, class: "link-mention" %> </p> 
        <p> <%= link_to "Antibes", root_path, class: "link-mention" %> </p>
        <p> <%= link_to "Mandelieu", root_path, class: "link-mention" %> </p> 
    </div>

</div>


<div class="row my-4">  
    <div class="col text-warning"> 
        <% if current_user && user_admin %>
            Admin
            <%= button_to "", destroy_user_session_path, method: :delete, class: "fa-solid fa-right-from-bracket btn btn-danger"  %>
        <% else %>
            <%= link_to '', new_user_session_path, 
                    class: "fa-solid fa-user-lock btn btn-warning" %>
            <%#= link_to '', new_user_registration_path, class: "fa-solid fa-user-plus btn btn-primary" %>
        <% end %>  
    </div>
</div>

<div class="row my-4 text-center text-light">  
    <div class="col"> 
        <%= render "shared/reseaux" %>
        <%= render "shared/contacts" %>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar sticky-top navbar-dark navbar-expand-lg py-0">
  <div class="container-fluid d-flex align-items-center">

    <%= link_to root_path, class: "no-underline middled" do %>
      <%= image_tag("galayacht-logo.webp", alt: "Logo", width: 25, height: 25, class: "rounded d-inline-block align-text-top") %>
      <span class="navbar-brand mx-2 fw-bold"> GALAYACHT </span>
    <% end %>
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav d-flex align-items-center">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <div data-turbo= "false">
            <%= link_to "Louer un bateau", produits_path, class: "nav-link" %>
          </div>
        </li>

        <li class="nav-item">
          <div data-turbo= "false">
            <%= link_to "Acheter un bateau", produits_path(type: "vente"), class: "nav-link" %>
          </div>
        </li>

        <li class="nav-item">
          <%= link_to "Proposer mon bateau", espace_bailleur_index_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
            <%= link_to "Evénements nautiques", evenement_index_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Destinations", destinations_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", new_demande_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "", "https://www.pinterest.fr/", 
            class:"fa-brands fa-pinterest btn-reseaux zoom nav-link", 
            alt: "Pinterest Galayacht",
            'aria-label' => "Ouvrir pinterest",
            target:"_blank" %>  
        </li>
        
        <li class="nav-item">
          <%= link_to "", "https://www.facebook.com/people/GALA-YACHT/100092488322369/", 
            class:"fa-brands fa-facebook btn-reseaux zoom nav-link", 
            alt: "Facebook Galayacht",
            'aria-label' => "Ouvrir facebook",
            target:"_blank" %>
        </li>

        <li class="nav-item">
          <%= link_to "", "https://www.instagram.com/galayacht/", 
              class:"fa-brands fa-instagram btn-reseaux zoom nav-link", 
              alt: "Instagram Galayacht",
             'aria-label' => "Ouvrir instagram",
              target:"_blank" %> 
        </li>

        <% if current_user && user_admin %>
          <li class="nav-item">
            <%= link_to "Admin", espace_admin_index_path, class: "nav-link text-warning" %>
          </li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/shared/_reseaux.html.erb
    <%= link_to "", "https://www.pinterest.fr/", 
        class:"fa-brands fa-pinterest btn-reseaux zoom", 
        alt: "Pinterest Galayacht",
        'aria-label' => "Ouvrir pinterest",
        target:"_blank" %>

    <%= link_to "", "https://www.facebook.com/people/GALA-YACHT/100092488322369/", 
            class:"fa-brands fa-facebook btn-reseaux zoom", 
            alt: "Facebook Galayacht",
            'aria-label' => "Ouvrir facebook",
            target:"_blank" %>

    <%= link_to "", "https://www.instagram.com/galayacht/", 
            class:"fa-brands fa-instagram btn-reseaux zoom", 
            alt: "Instagram Galayacht",
            'aria-label' => "Ouvrir instagram",
            target:"_blank" %> 

app/views/shared/_tui_calendar.html.erb
 <div id="divtoupdate"> 

    <script>
        var Calendar = tui.Calendar;
    </script>

    <div data-controller="calendar-tui">

        <div class="row p-2 text-center">
            <div class="col-2 text-center">
                <div id='current-month-link' class="btn btn-sm btn-primary view-link">
                    <i class="fas fa-calendar fa-xs"></i>
                
                </div>
            </div>
            <div class="col-8 justify-content-center">
            
                <div id='previous-link' class="btn btn-sm btn-outline-secondary view-link">
                    <i class="fas fa-arrow-left fa-xs"></i>
                    <span id="prev-month"></span>
                </div>

                <div id='current-link' class="btn btn-md btn-outline-secondary view-link">
                    <i class=""></i>
                    <span id="current-month"></span>
                </div>

                <div id='next-link' class="btn btn-sm btn-outline-secondary view-link">
                    <span id="next-month"></span>
                    <i class="fas fa-arrow-right fa-xs"></i>
                </div>

            </div>
            <div class="col-2 text-center">
                <div class="dropdown">
                    <button class="btn btn-sm btn-secondary dropdown-toggle m-0 p-1" type="button" data-bs-toggle="dropdown">
                        <i class="fas fa-display fa-xs"></i>
                        
                    </button>
                    <ul class="dropdown-menu">
                        <li><button class="dropdown-item view-link" type="button" id='day'>jour</button></li>
                        <li><button class="dropdown-item view-link" type="button" id='week'>semaine</button></li>
                        <li><button class="dropdown-item view-link" type="button" id='month'>mois</button></li>
                    </ul>
                </div>

            </div>
        </div>

    <%= tag.div nil, data: {schedules: @schedules.to_json}, 
        id: "calendar", 
        class: "container-calendar text-center" %>


    </div>

</div>