config/routes.rb
Rails.application.routes.draw do
 
  #hypens pour seo - link canonical dans layout 
  get 'location-bateau-cannes', to: 'article#location_bateau_cannes'
  get 'louer-bateau-cannes', to: 'article#location_bateau_cannes'
  #get 'article/location_bateau_cannes'

  get 'location-bateau-mandelieu', to: 'article#location_bateau_mandelieu'
  get 'louer-bateau-mandelieu', to: 'article#location_bateau_mandelieu'

  get 'location-bateau-antibes', to: 'article#location_bateau_antibes'
  get 'louer-bateau-antibes', to: 'article#location_bateau_antibes'
  
  get 'evenement-nautique-cote-d-azur-cannes-antibes-mandelieu', to: 'article#organisation_evenements'
  get 'sejour-en-mer-cote-d-azur-cannes-antibes-mandelieu-', to: 'article#organisation_evenements'
  get 'journee-en-bateau-cote-d-azur-cannes-antibes-mandelieu-', to: 'article#organisation_evenements'

  
  get 'evenement/index'
  
  get 'home/index'
  get 'home/indexdesign2'


  get "blog/index"

  get 'home/mentions_legales'
  get 'home/nous_connaitre'
  get 'home/politique_confidentialite'
  
  get 'home/testimage'
  root "home#index"
  get 'espace_permis/index'
  
  get 'espace_bailleur/index'
  get 'espace_preneur/index'
  get 'espace_admin/index'

  get 'produits/archive', to: 'produits#archive', as: 'archive_produits'
  post 'produits/:id/activate', to: 'produits#activate', as: 'activate_produit'
  post 'produits/:id/archivate', to: 'produits#archivate', as: 'archivate_produit'
  get '/produits/:id/fullscreen', to: 'produits#fullscreen', as: 'produit_fullscreen'
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'users/show'
  get 'users/:id' => 'users#show', as: 'user'
  
  resources :destinations
  resources :bailleurs
  resources :preneurs
  resources :admin_parameters
  resources :demandes
  
  resources :produits do
    member do
     # post :edit
      get :edition
      get :delete_image1_attachment
    #  get 'delete_media_attachment/:media_id', action: :delete_media_attachment, as: :delete_media_attachment
      get 'delete_media_attachment', to: 'produits#delete_media_attachment', as: :delete_media_attachment
 
    end
  end

  resources :contrats do 
    member do
      get :edition
      get :edition_capitaine
    end
  end


  resources :occupations do
    member do
      post :edit
    end
  end

  resources :schedules do
    member do
      post :edit
    end
  end

  resources :reservations do
    member do
      get :edition
      get :edition_test

      get :send_reservation_email_preneur, 
          to: 'reservations#send_reservation_email_preneur', 
          as: :send_reservation_email_preneur

      get :send_reservation_email_bailleur, 
          to: 'reservations#send_reservation_email_bailleur', 
          as: :send_reservation_email_bailleur
    end
  end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
 # def index
 #   @q = Produit.ransack(params[:q])
 #   @produits = @q.result(distinct: true)
 #   @destinations = Destination.all
 # end

  def index  
  end

  def mentions_legales
  end

  def nous_connaitre
  end

  def politique_confidentialite
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_form_recherche_bateau.html.erb
<div data-aos="zoom-in-up">
    <div class="card search-card">  
        <h2>
        	La location de bateau en toute simplicité 
        </h2>
        <div>
           Trouvez votre bateau idéal, où que vous soyez, quel que soit votre budget
        </div>

        <%= search_form_for @q, url: produits_path, method: :get do |f| %>

            <div class="form-group my-4">
            <%= f.label :city_cont, "Ville de départ", class: "fw-bold" %>
            <div class="input-group">
                <span class="input-group-text">
                <i class="fa fa-search"></i>
                </span>
                <%= f.search_field :city_cont, class: "form-control", placeholder: "Cannes, Antibes, Théoule, ..." %>
            </div>
            </div>


            <div class="form-group my-4">
                <%= f.label :type_produit_cont, "Type de bateau", class: "fw-bold" %>
                <%= f.search_field :type_produit_cont, class: "form-control", placeholder: "Moteur, voilier, catamaran, ..." %>
            </div>
            <div class="text-end">
                <%= f.submit "Search", class: "btn btn-primary my-2" %>
            </div>

        <% end %>

    </div>

</div>

app/views/home/ante_index.html.erb
<%# landing page avant log ou choix preneur bailleur %>




<%
=begin%>
 <% if current_user.present? %>
  <div class="button-container mb-3">
    <%= link_to "espace admin", espace_admin_index_path, class: "btn btn-dark m-1" if current_user.admin? %>
    <%#= link_to "espace propriétaire", espace_bailleur_index_path, class: "btn btn-primary m-1" if user_preneur.present? %>
    <%#= link_to "espace locataire", espace_preneur_index_path, class: "btn btn-warning m-1" if user_bailleur.present? %>
  </div>
<% end %> 
<%
=end%>


    <div data-aos="zoom-in-up" class="main-card my-4">
        <%= render "produits/form_recherche_bateau" %>
    </div>

    <div data-turbo= "false"> <%# fait fonctionner le carroussel %>

        <%= link_to espace_preneur_index_path, class: "no-underline" do %>
            <div data-aos="zoom-in-up" class="image-container my-4">
                <%= image_tag "/images/motor-boat.webp", class: "img-main", alt: "Aller vers louer un bateau" %> 
                <div class="text-overlay">
                    <h2>Louer un bateau</h2>
                    <p class="mt-2">  
                        Découvrez notre sélection de bateaux et de destinations
                    </p>
                </div>
            </div>
        <% end %>
    </div>

    
    <%= link_to espace_bailleur_index_path, class: "no-underline" do %>
        <div data-aos="zoom-in-up" class="image-container">
            <%= image_tag "/images/sail-boat.webp", class: "img-main", alt: "Aller vers proposer un bateau"  %> 
            <div class="text-overlay">
                <h2>Proposer un bateau</h2>
                <p class="mt-2">  
                    Retrouvez nos outils pour proposer votre bateau à la location
                </p>
            </div>
        </div>
    <% end %>  

app/views/home/ante_videos_index.html.erb
<% description "Bienvenue chez Galayacht. Solution facile pour louer un bateau ou un yacht et plus à Cannes, Mandelieu, Antibes." %>
<% keywords "Antibes, location de bateau, louer yacht, louer bateau, location bateau cote azur, louer bateau mandelieu" %>

<h1 style="position: absolute; left: -9999px;"> 
  Accueil Galayacht - Location bateau Mandelieu - Antibes - Cannes 
</h1>

<div class="video-container">
    <div data-controller="video">
        <!--video loop muted playsinline id="video-background" data-video-target="video">
            <source src="/videos/sea-1-mini.mp4" type="video/mp4">
        </video-->
    
        <video autoplay loop muted playsinline
           src="https://res.cloudinary.com/dukne3lhz/video/upload/v1695539896/sea-1-mini-muted_j4q1xp.mp4" 
           type="video/mp4" id="video-background" data-video-target="video" > 
        </video>
    </div>

    <span class="d-flex flex-wrap justify-content-center">
    
        <div class="form-container d-block">
            <h3 class="text-center fw-bold mt-4 title-styled">
            Trouvez votre bateau idéal

                <div class="" data-turbo="false"> <%# fait fonctionner le carroussel %>
                    <%= link_to "Voir tous les bateaux", produits_path, class: "btn primary-colored fw-bold my-4 large-btn-sized" %>
                </div>
            </h3>
            <%= render "produits/form_recherche_bateau" %>
        </div>
    </span>
</div>
<div class="video-container">
    <div data-controller="video">
        <!--video autoplay loop muted playsinline id="video-background" data-video-target="video">
            <source src="/videos/sea-2-mini.mp4" type="video/mp4">
        </video-->
        <video autoplay loop muted playsinline
           src="https://res.cloudinary.com/dukne3lhz/video/upload/v1695539897/sea-2-mini-muted_ebt3lv.mp4" 
           type="video/mp4" id="video-background" data-video-target="video" > 
        </video>
   </div>
    <span class="d-flex flex-wrap justify-content-center">
        <div class="form-container primary-colored">   
            <div data-turbo="false"> <%# fait fonctionner le carroussel %>
         
                <%= link_to produits_path, class: "no-underline" do %>
                    <h2 class="title-styled mb-4">Louer un bateau</h2>
                    <p class="mt-2 fs-4 fw-bold text-dark text-center">  
                        Découvrez la sélection Galayacht de bateaux et de destinations
                    </p>

                <p class="my-3 btn primary-colored fw-bold w-100 btn-text-styled">
                   Voir les bateaux
                </p>
                    
                <% end %>
            </div>
        </div>
    </span>
</div>
<div class="video-container">
    <div data-controller="video">
        <!--video autoplay loop muted playsinline id="video-background" data-video-target="video">
            <source src="/videos/sea-3-mini.mp4" type="video/mp4">
        </video-->

        <video autoplay loop muted playsinline
           src="https://res.cloudinary.com/dukne3lhz/video/upload/v1695539897/sea-3-mini-muted_gbyxjl.mp4" 
           type="video/mp4" id="video-background" data-video-target="video" > 
        </video>
    </div>
    <span class="d-flex flex-wrap justify-content-center">
        <div class="form-container primary-colored">            
            <%= link_to espace_bailleur_index_path, class: "no-underline " do %>
                <h2 class="title-styled mb-4">Proposer un bateau</h2>
                <p class="mt-2 fs-4 fw-bold text-dark text-center">  
                    Retrouvez nos outils pour proposer votre bateau à la location
                </p>
                <p class="my-3 btn primary-colored fw-bold w-100 btn-text-styled">
                    En savoir plus
                </p>
            <% end %>
        </div>
    </span>
</div>

app/views/home/index.html.erb
<h1 style="position: absolute; left: -9999px;"> 
  Location bateau Cannes Golfe Juan Antibes Mandelieu 
</h1>


<div class="video-container position-relative">
    <div data-controller="video">
        <video autoplay loop muted playsinline
           src="https://res.cloudinary.com/dukne3lhz/video/upload/v1695994418/pexels-abe-bagyan-9454551_720p_hhrb8w.mp4" 
           type="video/mp4" id="video-background" data-video-target="video">
        </video>
    </div>

    <div class="text-container position-absolute bottom-0 w-100 px-4">
        <h2 class="title-styled mb-4 text-start">
            Retrouvez les bateaux et services proposés par GALAYACHT
            <div data-turbo="false"> <%# fait fonctionner le carroussel %>
                <%= link_to "Voir tous les bateaux", produits_path, class: "btn btn-light fw-bold my-2 px-5" %>
            </div>
        </h2>
    </div>
</div>

<div class="container-fluid bg-black overflow-hidden">
  <div data-turbo="false" class="row row-cols-1 row-cols-md-2">

    <div data-aos="zoom-in" class="col border-black p-0 position-relative bloc-topic">
        <%= link_to produits_path(q: { location_eq: true }) do %>
            <%= image_tag("https://res.cloudinary.com/dukne3lhz/image/upload/v1695993409/boat2_og5ivm.webp", 
                class: "img-fluid w-100 h-100",
                alt: "location bateau sur mer calme à Cannes Mandelieur Golfe Juan") %>
            <div class="position-absolute bottom-0 start-0 end-0 text-start text-white p-2">
                <strong class="fs-5 fw-bold"> LOUER UN BATEAU</strong>
                <div class="sous-titre-topic"> Notre sélection de bateaux disponibles à la location</div>
                <div class="btn btn-sm btn-light my-2 text-medium-sized"> Voir les locations</div>
            </div>
        <% end %>
    </div>
    <div data-aos="zoom-in" class="col border-black p-0 position-relative bloc-topic">
        <%= link_to produits_path(q: { vente_eq: true }) do %>
            <%= image_tag("https://res.cloudinary.com/dukne3lhz/image/upload/v1695993411/boat8_oztelv.webp", 
                class: "img-fluid w-100 h-100",
                alt: "bateau à moteur proche de la côte") %>
            <div class="position-absolute bottom-0 start-0 end-0 text-start text-white p-2">
                <strong class="fs-5 fw-bold"> ACHETER UN BATEAU</strong>
                <div class="sous-titre-topic"> Notre sélection de bateaux disponibles à la vente</div>
                <div class="btn btn-sm btn-light my-2 text-medium-sized"> Voir les ventes</div>
            </div>
        <% end %>
    </div>
    
    <div data-aos="zoom-in" class="col border-black p-0 position-relative bloc-topic">
        <%= link_to evenement_index_path do %>
            <%= image_tag("https://res.cloudinary.com/dukne3lhz/image/upload/v1695993414/boat7_f61sxa.webp", 
                class: "img-fluid w-100 h-100",
                alt: "événément nautique séjour avec groupe de personnes sur un bateau") %>
            <div class="position-absolute bottom-0 start-0 end-0 text-start text-white p-2">
                <strong class="fs-5 fw-bold"> EVENEMENTS NAUTIQUES</strong>
                <div class="sous-titre-topic"> Toutes les informations sur l'organisation de journées et séjours personnels ou professionnels</div>
                <div class="btn btn-sm btn-light my-2 text-medium-sized"> En savoir plus</div>
            </div>
        <% end %>
    </div>

    <div data-aos="zoom-in" class="col border-black p-0 position-relative bloc-topic">
        <%= link_to destinations_path do %>
            <%= image_tag("https://res.cloudinary.com/dukne3lhz/image/upload/v1695993412/boat-port_bbsvxg.webp", 
                class: "img-fluid w-100 h-100",
                alt: "bateaux ports de Cannes Mandelieur Golfe Juan") %>
            <div class="position-absolute bottom-0 start-0 end-0 text-start text-white p-2">
                <strong class="fs-5 fw-bold"> DESTINATIONS</strong>
                <div class="sous-titre-topic"> Notre sélection de destinations et villes de départ</div>
                <div class="btn btn-sm btn-light my-2 text-medium-sized"> Découvrir les destinations</div>
            </div>
        <% end %>
    </div>

    <div data-aos="zoom-in" class="col border-black p-0 position-relative bloc-topic">
        <%= link_to espace_bailleur_index_path do %>
            <%= image_tag("https://res.cloudinary.com/dukne3lhz/image/upload/v1695993785/boat9_t0prtt.webp", 
                class: "img-fluid w-100 h-100",
                alt: "bateau à moteur dans une crique") %>
            <div class="position-absolute bottom-0 start-0 end-0 text-start text-white p-2">
                <strong class="fs-5 fw-bold"> PROPOSER UN BATEAU</strong>
                <div class="sous-titre-topic"> Retrouvez nos outils pour proposer votre bateau à la location ou à la vente</div>
                <div class="btn btn-sm btn-light my-2 text-medium-sized">  En savoir plus</div>
            </div>
        <% end %>
    </div>

    <div data-aos="zoom-in" class="col border-black p-0 position-relative bloc-topic">
      <%= link_to new_demande_path do %>
          <%= image_tag("https://res.cloudinary.com/dukne3lhz/image/upload/v1695993413/boat-contact_itqpgo.webp", 
              class: "img-fluid w-100 h-100",
              alt: "bateau origami") %>
          <div class="position-absolute bottom-0 start-0 end-0 text-start text-white p-2">
              <strong class="fs-5 fw-bold"> CONTACTER GALAYACHT</strong>
              <div class="sous-titre-topic"> Contactez nous directement ou laissez nous un message</div>
              <div class="btn btn-sm btn-light my-2 text-medium-sized"> Contact </div>
          </div>
      <% end %>
    </div>

  </div>
</div>

app/views/home/mentions_legales.html.erb
<div class="max-widthed">   

    <h2 class="text-center">Mentions légales</h2>

    <div class="container py-4">

        Nous vous prions de lire avec attention les différentes modalités d’utilisation du présent site avant de parcourir ses pages. 

        En vous connectant sur ce site, vous acceptez sans réserve les modalités qui suivent.

        <h3>  Editeur du Site </h3>

        GALAYACHT.com <br>
        Responsable : <br>
        Siège social : <br>
        Téléphone : <br>
        Email : <br>
        Site Web : https://galayacht.com/<br>

        <h3 class="my-4"> Hébergement  </h3>

        Hébergeur : le présent site est hébergé chez XXX

        <h2> Conditions d'utilisation  </h2>

        <h3>Langages web recommandés  </h3>
        <p>
            Pour un meilleur confort d'utilisation et un graphisme agréable, nous recommandons l'utilisation de navigateurs modernes tels que Internet Explorer, Safari, Firefox, Google Chrome, etc.
        </p>

        <h3>Exactitude des informations  </h3>
        <p>
            GALAYACHT s'efforce de fournir des informations fiables et mises à jour sur ses sites internet. Cependant, des erreurs ou omissions peuvent survenir. Les utilisateurs doivent vérifier l'exactitude des informations auprès de GALAYACHT et signaler toute modification jugée nécessaire.
        </p>
        <h3>Responsabilité de l'utilisation des informations  </h3>
        <p>
            GALAYACHT n'est en aucun cas responsable de l'utilisation faite des informations fournies sur ses sites internet et de tout préjudice direct ou indirect qui pourrait en découler.
        </p>

        <h3>Cookies  </h3>
        <p>
            Le site galayacht.com peut utiliser des cookies à des fins statistiques et d'affichage. Un cookie est un fichier texte stocké sur votre ordinateur qui permet au serveur du site de lire et d'enregistrer certaines informations. Certaines parties du site peuvent nécessiter l'acceptation des cookies pour fonctionner correctement.
        </p>

        <h3>Liens hypertextes  </h3>
        <p>
            Les sites internet peuvent contenir des liens vers d'autres ressources en ligne. GALAYACHT n'a aucun contrôle sur ces sites et ne garantit pas leur disponibilité. Elle décline toute responsabilité quant au contenu de ces sites ou sources externes, y compris les informations, produits ou services qu'ils proposent. L'utilisation de ces éléments se fait aux risques de l'internaute, qui doit se conformer à leurs conditions d'utilisation.
        </p>

        <h3>Hyperliens vers le site  </h3>
        <p>
            Toute création d'un hyperlien vers le site de GALAYACHT nécessite une autorisation expresse et préalable de cette dernière.
        </p>

        <h3>Services fournis  </h3>
        <p>
            Le site galayacht.com présente les activités et informations de la société GALAYACHT. Les informations fournies sur le site sont données à titre indicatif et peuvent être modifiées sans préavis. Les photos sont non contractuelles.
        </p>

        <h3>Limitations contractuelles sur les données  </h3>
        <p>
            Bien que le site soit mis à jour régulièrement, il peut contenir des inexactitudes ou des omissions. Si vous constatez un problème, veuillez le signaler par email à contact@galayacht.fr en fournissant des détails précis sur le problème rencontré.
        </p>

        <h3>Responsabilité des téléchargements et de l'utilisation du site  </h3>
        <p>
            Tout téléchargement de contenu se fait aux risques de l'utilisateur. GALAYACHT décline toute responsabilité en cas de dommage à l'ordinateur de l'utilisateur ou de perte de données résultant du téléchargement. L'utilisateur s'engage à utiliser un matériel récent, exempt de virus et à jour.
        </p>

        <h3>Propriété intellectuelle   </h3>
        <p>
            Le contenu du site galayacht.com, y compris les graphismes, images, textes, vidéos, animations, sons, logos, gifs et icônes, est la propriété exclusive de GALAYACHT, sauf indication contraire. Toute reproduction, distribution, modification, adaptation, retransmission ou publication de ces éléments, même partielle, est strictement interdite sans l'accord écrit de GALAYACHT.
        </p>

        <h3>Données personnelles </h3>

        <h4>Collecte de données  </h4>
        <p>
            Lors de l'utilisation de certains services proposés sur notre site galayacht.com, il peut vous être demandé de fournir des informations personnelles telles que votre nom, votre fonction, le nom de votre société, votre adresse électronique et votre numéro de téléphone. Cela peut se produire lorsque vous remplissez un formulaire en ligne dans la rubrique "Contact" ou lors de la réservation d'un bateau.
        </p>

        <h4>Refus de fournir des données personnelles  </h4>
        <p>
            Vous avez la possibilité de refuser de fournir vos données personnelles. Cependant, dans ce cas, vous ne pourrez pas utiliser certains services du site, notamment ceux liés à la demande de renseignements sur notre société, à la location d'un bateau ou à la réception de newsletters.
        </p>

        <h4>Collecte automatique d'informations  </h4>
        <p>
            Lors de votre simple navigation sur notre site Internet, certaines informations vous concernant peuvent être collectées automatiquement, telles que des données sur l'utilisation du site (pages visitées, services utilisés), votre adresse IP, le type de navigateur utilisé et les temps d'accès. Ces informations sont exclusivement utilisées à des fins de statistiques internes dans le but d'améliorer la qualité des services proposés.
        </p>

        <h4>Protection des données  </h4>
        <p>
            Les bases de données sont protégées conformément aux dispositions de la loi du 1er juillet 1998 transposant la directive 96/9 du 11 mars 1996 relative à la protection juridique des bases de données.
        </p>
    </div>

</div>

app/views/home/nous_connaitre.html.erb
<div class="max-widthed">   

    <h3>Nous connaitre</h3>

    <div class="container py-4">


        <hr>

        <p>Bienvenue chez GALAYACHT, votre partenaire de confiance pour la location de yachts à Cannes et le long de la magnifique côte d'Azur. Nous sommes une équipe passionnée composée de professionnels expérimentés qui ont pour objectif de vous offrir une expérience inoubliable dans le monde du nautisme.</p>

        <h3>Notre Mission</h3>
        <p>Notre mission est de vous accompagner du mieux possible dans la concrétisation de votre projet de location de yacht. Que vous souhaitiez organiser une sortie en mer, une croisière de luxe ou une réception privée, nous mettons tout en œuvre pour répondre à vos attentes et dépasser vos exigences.</p>

        <h3>Partenariat avec les propriétaires de yachts d'exception</h3>
        <p>Pour garantir des prestations de qualité, nous collaborons étroitement avec les propriétaires des plus beaux yachts du monde du nautisme. Ces partenariats nous permettent de vous offrir un vaste choix de yachts de luxe, allant des élégants voiliers aux somptueux yachts à moteur, tous entretenus avec soin et dotés des équipements les plus modernes.</p>

        <h3>Des services sur mesure</h3>
        <p>Nous comprenons que chaque client a des besoins et des préférences uniques. C'est pourquoi nous nous engageons à vous offrir des services sur mesure qui correspondent parfaitement à vos attentes. Notre équipe dévouée est à votre écoute pour comprendre vos besoins, vous conseiller et vous aider à choisir le yacht idéal pour votre location.</p>

        <h3>Expérience de navigation exceptionnelle</h3>
        <p>En choisissant GALAYACHT Yachting, vous bénéficiez non seulement d'une flotte de yachts d'exception, mais également d'une expérience de navigation exceptionnelle. Vous aurez l'opportunité de découvrir les eaux cristallines de la Méditerranée, de visiter des destinations prestigieuses telles que Saint-Tropez, Monaco, Antibes et bien d'autres encore, tout en bénéficiant d'un service personnalisé et attentif à bord de nos yachts.</p>

        <h3>Respect de votre vie privée et protection des données</h3>
        <p>Nous attachons une grande importance à la protection de vos données personnelles. Lorsque vous utilisez notre site web ou que vous nous fournissez des informations lors de la réservation d'un yacht, nous veillons à respecter votre vie privée et à traiter vos données de manière confidentielle, conformément aux lois en vigueur.</p>

        <h3>Contactez-nous dès maintenant</h3>
        <p>Que vous souhaitiez organiser une escapade en mer, une célébration spéciale ou une journée de détente avec vos proches, notre équipe est prête à vous aider à concrétiser votre projet de location de yacht à Cannes ou sur la côte d'Azur. Contactez-nous dès maintenant pour discuter de vos besoins et réserver le yacht de vos rêves. Nous nous réjouissons de vous offrir une expérience inoubliable sur les eaux azuréennes.</p>

        <hr>

        <%= render "shared/contacts" %>
        <hr>

    </div>

</div>

app/views/home/politique_confidentialite.html.erb
<div class="max-widthed">   

    <h1 class="h1-styled"> class="mb-4">Politique de confidentialité</h1>

    <div class="container py-4">

        <h2>Collecte de données personnelles</h2>
        <p>
            Bienvenue sur le site web de Galayacht !
        </p>
        <p>
            Nous prenons votre vie privée très au sérieux et nous nous engageons à protéger vos informations personnelles. Cette politique de confidentialité explique comment nous collectons, utilisons et protégeons les données que vous nous fournissez lorsque vous utilisez notre site web.
        </p>
        
        <h2>Collecte de données personnelles</h2> 
        <p>
            Lorsque vous laissez un commentaire sur notre site web, nous collectons les informations que vous avez fournies dans le formulaire de commentaire, ainsi que votre adresse IP et les détails de votre navigateur, afin de détecter les commentaires indésirables.
        </p>
        <p>
            Si vous téléversez des images sur notre site en tant qu'utilisateur enregistré, nous vous recommandons d'éviter de téléverser des images contenant des données de localisation GPS. Les visiteurs de notre site pourraient extraire ces données de localisation depuis les images.
        </p>

        <h2>Utilisation des cookies</h2>
        <p>
            Lorsque vous déposez un commentaire sur notre site, vous avez la possibilité d'enregistrer votre nom, votre adresse e-mail et votre site web dans des cookies. Cela facilite votre utilisation future du site en évitant d'avoir à saisir à nouveau ces informations. Ces cookies expirent au bout d'un an.
        </p>
        <p>
            Lorsque vous vous connectez à votre compte, nous utilisons des cookies pour enregistrer vos informations de connexion et vos préférences d'écran. Ces cookies ont une durée de vie de deux jours. Si vous sélectionnez l'option "Se souvenir de moi", votre cookie de connexion sera conservé pendant deux semaines. Lorsque vous vous déconnectez de votre compte, le cookie de connexion est supprimé.
        </p>
        <h2>Contenu intégré depuis d'autres sites web </h2>
        <p>
            Certains articles de notre site peuvent inclure du contenu intégré (par exemple des vidéos, des images, des articles) provenant d'autres sites web. Ce contenu se comporte de la même manière que si vous visitiez directement ces autres sites web.
        </p>
        <p>
            Ces sites web tiers peuvent collecter des données vous concernant, utiliser des cookies et suivre vos interactions avec leur contenu intégré, notamment si vous disposez d'un compte connecté sur leur site web.
        </p>

        <h2>Stockage et durée de conservation des données </h2>
        <p>
            Si vous laissez un commentaire sur notre site, votre commentaire et ses métadonnées sont conservés indéfiniment. Cela nous permet d'approuver automatiquement les commentaires suivants au lieu de les placer en file d'attente de modération.
        </p>
        <p>
            Pour les utilisateurs enregistrés sur notre site, nous stockons également les données personnelles indiquées dans leur profil. Vous pouvez accéder à ces informations, les modifier ou les supprimer à tout moment, à l'exception de votre nom d'utilisateur. Les gestionnaires du site ont également accès et peuvent modifier ces informations.
        </p>

        <h2>Vos droits sur vos données personnelles </h2>
        <p>
            Si vous avez un compte sur notre site ou si vous avez laissé des commentaires, vous pouvez demander à recevoir un fichier contenant toutes les données personnelles que nous détenons à votre sujet, y compris celles que vous nous avez fournies. Vous pouvez également demander la suppression de vos données personnelles. Veuillez noter que certaines données peuvent être conservées à des fins administratives, légales ou de sécurité.
        </p>
    </div>

</div>