config/routes.rb
Rails.application.routes.draw do
 
  #hypens pour seo - link canonical dans layout 
  get 'location-bateau-cannes', to: 'article#location_bateau_cannes'
  get 'louer-bateau-cannes', to: 'article#location_bateau_cannes'
  #get 'article/location_bateau_cannes'

  get 'location-bateau-mandelieu', to: 'article#location_bateau_mandelieu'
  get 'louer-bateau-mandelieu', to: 'article#location_bateau_mandelieu'

  get 'location-bateau-antibes', to: 'article#location_bateau_antibes'
  get 'louer-bateau-antibes', to: 'article#location_bateau_antibes'
  
  get 'evenement-nautique-cote-d-azur-cannes-antibes-mandelieu', to: 'article#organisation_evenements'
  get 'sejour-en-mer-cote-d-azur-cannes-antibes-mandelieu-', to: 'article#organisation_evenements'
  get 'journee-en-bateau-cote-d-azur-cannes-antibes-mandelieu-', to: 'article#organisation_evenements'

  
  get 'evenement/index'
  
  get 'home/index'
  get 'home/indexdesign2'


  get "blog/index"

  get 'home/mentions_legales'
  get 'home/nous_connaitre'
  get 'home/politique_confidentialite'
  
  get 'home/testimage'
  root "home#index"
  get 'espace_permis/index'
  
  get 'espace_bailleur/index'
  get 'espace_preneur/index'
  get 'espace_admin/index'

  get 'produits/archive', to: 'produits#archive', as: 'archive_produits'
  post 'produits/:id/activate', to: 'produits#activate', as: 'activate_produit'
  post 'produits/:id/archivate', to: 'produits#archivate', as: 'archivate_produit'
  get '/produits/:id/fullscreen', to: 'produits#fullscreen', as: 'produit_fullscreen'
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'users/show'
  get 'users/:id' => 'users#show', as: 'user'
  
  resources :destinations
  resources :bailleurs
  resources :preneurs
  resources :admin_parameters
  resources :demandes
  
  resources :produits do
    member do
     # post :edit
      get :edition
      get :delete_image1_attachment
    #  get 'delete_media_attachment/:media_id', action: :delete_media_attachment, as: :delete_media_attachment
      get 'delete_media_attachment', to: 'produits#delete_media_attachment', as: :delete_media_attachment
 
    end
  end

  resources :contrats do 
    member do
      get :edition
      get :edition_capitaine
    end
  end


  resources :occupations do
    member do
      post :edit
    end
  end

  resources :schedules do
    member do
      post :edit
    end
  end

  resources :reservations do
    member do
      get :edition
      get :edition_test

      get :send_reservation_email_preneur, 
          to: 'reservations#send_reservation_email_preneur', 
          as: :send_reservation_email_preneur

      get :send_reservation_email_bailleur, 
          to: 'reservations#send_reservation_email_bailleur', 
          as: :send_reservation_email_bailleur
    end
  end



end

app/models/preneur.rb
class Preneur < ApplicationRecord
    has_one_attached :profilepic

    belongs_to :user

    validates :nom, presence: true
    validates :telephone, presence: true, if: -> { mail.blank? }
    validates :mail, presence: true, if: -> { telephone.blank? }

    def full_name
        "#{prenom} #{nom}"
    end

end

app/controllers/preneurs_controller.rb
class PreneursController < ApplicationController
  include UserHelper
  before_action :set_preneur, only: %i[ show edit update destroy ]
  before_action :authorize_admin

  def index
    @preneurs = Preneur.all
  end

  def show
  end

  def new
    @preneur = Preneur.new
  end

  def edit
  end

  def create
    @preneur = Preneur.new(preneur_params)

    respond_to do |format|
      if @preneur.save
        flash[:success] = "locataire was successfully created."
        format.html { redirect_to preneur_url(@preneur) }
        format.json { render :show, status: :created, location: @preneur }
      else
        flash[:error] = "locataire could not be created."
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @preneur.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @preneur.update(preneur_params)
        flash[:success] = "locataire was successfully updated."
        format.html { redirect_to preneur_url(@preneur) }
        format.json { render :show, status: :ok, location: @preneur }
      else
        flash[:error] = "locataire could not be updated."
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @preneur.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @preneur.destroy

    respond_to do |format|
      flash[:success] = "locataire was successfully destroyed."
      format.html { redirect_to preneurs_url}
      format.json { head :no_content }
    end
  end

  private
    def set_preneur
      @preneur = Preneur.find(params[:id])
    end

    def preneur_params
      params.require(:preneur).permit(:prenom, :nom, :adresse, :telephone, :mail, :user_id, :profilepic)
    end

    def authorize_admin
      unless current_user && user_admin
        redirect_to root_path, alert: "You are not authorized to access this page."
      end
    end
end

app/helpers/preneurs_helper.rb
module PreneursHelper

    def preneur_full_name(preneur)
       "#{Preneur.find(preneur).prenom} #{Preneur.find(preneur).nom}"
    end
end

app/views/preneurs/_form.html.erb
<%= form_with(model: preneur) do |form| %>
  <% if preneur.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(preneur.errors.count, "error") %> prohibited this preneur from being saved:</h2>

      <ul>
        <% preneur.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group">
    <%= form.label :prenom, class: "input-group-text label-with-format" %>
    <%= form.text_field :prenom, class: "form-control field-with-format" %>
  </div>

  <div class="input-group">
    <%= form.label :nom, class: "input-group-text label-with-format" %>
    <%= form.text_field :nom, class: "form-control field-with-format" %>
  </div>

  <div class="input-group">
    <%= form.label :adresse, class: "input-group-text label-with-format" %>
    <%= form.text_field :adresse, class: "form-control field-with-format" %>
  </div>

  <div class="input-group">
    <%= form.label :telephone, class: "input-group-text label-with-format" %>
    <%= form.text_field :telephone, class: "form-control field-with-format" %>
  </div>

  <div class="input-group">
    <%= form.label :mail, class: "input-group-text label-with-format" %>
    <%= form.text_field :mail, class: "form-control field-with-format" %>
  </div>

  <div class="input-group">
    <%#= form.label :user, class: "input-group-text label-with-format" %>
    <%= form.hidden_field :user_id, value: current_user.id, class: "form-control field-with-format" %>
  </div>

  <div class="input-group mb-1">
    <%= form.label :image, class:"input-group-text label-with-format" %>
    <%= form.file_field :profilepic, class:"form-control field-with-format" %>
  </div>
  
  <hr>
  <div class="col text-end">
    <%= render "shared/form_submit" %> 
  </div>

<% end %>

app/views/preneurs/_preneur.html.erb
  <div id="<%= dom_id preneur %>">

    <div class="card produit-card">
      <div class="row g-0">
        <div class="col-md-12">
          <div class="card-body">
            <h5 class="card-title"> <%= preneur.prenom %>  <%= preneur.nom %> </h5>
            <p class="card-text">
              <i class="fa fa-home"></i>
              <%= preneur.adresse %>   
              <hr>
              <i class="fa fa-phone"></i>
              <%= preneur.telephone %>   
              <hr>
              <i class="fa fa-envelope"></i>
              <%= preneur.mail %>           
            </p>
            <p class="card-text"><small class="text-muted">Since <%= preneur.created_at %></small></p>
          </div>
        </div>
      </div>
      <hr>
      <div class="container-fluid text-end p-2">
        <div class="row"> 
          <div class="col-12 text-end">
            <%= link_to "", edit_preneur_path(preneur), class: "btn btn-sm btn-secondary fa-solid fa-pen-to-square" %>
            <%= link_to "", preneur_path(preneur), class: "btn btn-sm btn-primary fa-solid fa-eye" %>
          </div>
        </div>
      </div>
    </div>

</div>

app/views/preneurs/edit.html.erb
<h4 class="mt-5">Profile locataire</h4>

<%= render "form", preneur: @preneur %>

<br>

<div>
  <%#= link_to "Show this preneur", @preneur %> 
  <%#= link_to "Back to preneurs", preneurs_path %>
</div>

app/views/preneurs/index.html.erb
<h1>Preneurs</h1>

 <div id="preneurs" class="container-fluid">
  <div class="row justify-content-center">
    <% @preneurs.each do |preneur| %>
      <div class="col-sm-6 col-md-4 col-lg-3 d-flex align-items-center justify-content-center mb-3">
         <%= render preneur %> 
      </div>
    <% end %>
  </div>
</div> 

<% if current_user && user_admin %>
  <%= link_to "New preneur", new_preneur_path, class: "btn btn-warning" %>
<% end %>

app/views/preneurs/new.html.erb
<h3>Créer votre profile Locataire</h3>

<%= render "form", preneur: @preneur %>

<br>

app/views/preneurs/show.html.erb
<div class="mt-5">  
  <%= render @preneur %>
</div>

<% if current_user && user_admin %>
  <%= button_to @preneur, method: :delete, class: "btn btn-action btn-outline-danger",
      data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
      <i class="fa-solid fa-trash me-2"></i>
      <span class="fw-bold"> Supprimer ce preneur </span>
  <% end %>
<% end %>